Lint improve 2

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -12,17 +12,32 @@ jobs:
       - name: Checkout code
         uses: actions/checkout@v2
       - name: Install dependencies
-        run: go get -u golang.org/x/lint/golint
+        run: |
+          go get -u golang.org/x/lint/golint
+          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $HOME/go/bin/ latest
       - name: Run build
         run: go build .
       - name: Run vet
         run: go vet .
       - name: Run golint
-        run: golint .
+        run: golint -set_exit_status .
       - name: Run golangci-lint
+        run: golangci-lint run -v
+      - name: Run checks
         run: |
-          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $HOME/go/bin/ latest
-          golangci-lint run -v
+          STATUS=0
+          assert-nothing-changed() {
+            local diffexit $STATUS
+            "$@" >/dev/null || return 1
+            if ! diff="$(git diff -U1 --color --exit-code)"; then
+              printf '\e[31mError: running `\e[1m%s\e[22m` results in modifications that you must check into version control:\e[0m\n%s\n\n' "$*" "$diff" >&2
+              git checkout -- .
+              STATUS=1
+            fi
+          }
+          assert-nothing-changed go fmt ./...
+          assert-nothing-changed go mod tidy
+          exit $STATUS
 
   test:
     runs-on: ubuntu-latest
